### ISSUE TITLE
Design a new logo for the project

### ISSUE THREAD

**Issue by omaralbeik** [MobilionOSS/PieCrust#26]

**Comment by lionbytes** [comment]
![title](https://user-images.githubusercontent.com/9406603/37248330-83b524ea-24e0-11e8-88fd-f2e9dac04154.png)

![asd](https://user-images.githubusercontent.com/9406603/37248345-2c413bda-24e1-11e8-8c2a-021fb1b0df4b.png)

# PieCrust Logo

Similar colors to **Swift**'s colors. Horizontal and vertical crust stripes represent grids of layouts.
Font chosen to be technical and not aesthetic so the visual identity is not mistaken for an actual pie product/service.

**Comment by omaralbeik** [comment]
@lionbytes I'd be grateful if you:
1. fork the project
2. replace `logo.svg` with a new one (please note the logo should be without a background and text should be transformed to outlines)
3. add all fonts used in the design to `Assets/Fonts`
4. add any design source file (`.psd`, `.ai`, ...) to `Assets/Sources`
5. submit a new pull request, and I'll make sure to get it merged in in no time 🙂

**Comment by omaralbeik** [comment]
@soyhanbeyazit 👆, 💯

**Comment by lionbytes** [comment]
@omaralbeik You got it.
